state_replacement_dict = {
    u'Mississippi':          u'MS',
    u'Oklahoma':             u'OK',
    u'Delaware':             u'DE',
    u'Minnesota':            u'MN',
    u'Illinois':             u'IL',
    u'Arkansas':             u'AR',
    u'New Mexico':           u'NM',
    u'Indiana':              u'IN',
    u'Maryland':             u'MD',
    u'Louisiana':            u'LA',
    u'Idaho':                u'ID',
    u'Wyoming':              u'WY',
    u'Tennessee':            u'TN',
    u'Arizona':              u'AZ',
    u'Iowa':                 u'IA',
    u'Michigan':             u'MI',
    u'Kansas':               u'KS',
    u'Utah':                 u'UT',
    u'Virginia':             u'VA',
    u'Oregon':               u'OR',
    u'Connecticut':          u'CT',
    u'Montana':              u'MT',
    u'California':           u'CA',
    u'Massachusetts':        u'MA',
    u'West Virginia':        u'WV',
    u'South Carolina':       u'SC',
    u'New Hampshire':        u'NH',
    u'Wisconsin':            u'WI',
    u'Vermont':              u'VT',
    u'Georgia':              u'GA',
    u'North Dakota':         u'ND',
    u'Pennsylvania':         u'PA',
    u'Florida':              u'FL',
    u'Alaska':               u'AK',
    u'Kentucky':             u'KY',
    u'Hawaii':               u'HI',
    u'Nebraska':             u'NE',
    u'Missouri':             u'MO',
    u'Ohio':                 u'OH',
    u'Alabama':              u'AL',
    u'Rhode Island':         u'RI',
    u'South Dakota':         u'SD',
    u'Colorado':             u'CO',
    u'New Jersey':           u'NJ',
    u'Washington':           u'WA',
    u'North Carolina':       u'NC',
    u'New York':             u'NY',
    u'District of Columbia': u'DC',
    u'Texas':                u'TX',
    u'Nevada':               u'NV',
    u'Maine':                u'ME',
}

state_replacement_dict.update({
    u'DE, DE':               u'DE',
    u'DE DE':                u'DE',
    u'DC, DC':               u'DC',
    u'DC, MD':               u'DC',
})
