# Upper case the string before testing
# Generated from the USPS table at http://pe.usps.gov/text/pub28/28apc_002.htm

# Follow pattern:
# Cannonical Name: Names to convert to 'Cannonical Name'
# Converted into dict below
street_type_replacement_list = [
    (u'ALY',    (u'ALY', u'ALLY', u'ALLEY', u'ALLEE')),
    (u'ANX',    (u'ANNX', u'ANEX', u'ANNEX', u'ANX')),
    (u'ARC',    (u'ARC', u'ARCADE')),
    (u'AVE',    (u'AVN', u'AVENU', u'AVENUE', u'AVE', u'AVNUE', u'AVEN',
                 u'AV')),
    (u'BCH',    (u'BEACH', u'BCH')),
    (u'BG',     (u'BURG',)),
    (u'BGS',    (u'BURGS',)),
    (u'BLF',    (u'BLF', u'BLUFF', u'BLUF')),
    (u'BLFS',   (u'BLUFFS',)),
    (u'BLVD',   (u'BOULEVARD', u'BOUL', u'BOULV', u'BLVD')),
    (u'BND',    (u'BEND', u'BND')),
    (u'BR',     (u'BRNCH', u'BRANCH', u'BR')),
    (u'BRG',    (u'BRIDGE', u'BRDGE', u'BRG')),
    (u'BRK',    (u'BROOK', u'BRK')),
    (u'BRKS',   (u'BROOKS',)),
    (u'BTM',    (u'BOTTOM', u'BOTTM', u'BTM', u'BOT')),
    (u'BYP',    (u'BYP', u'BYPAS', u'BYPASS', u'BYPA', u'BYPS')),
    (u'BYU',    (u'BAYOO', u'BAYOU')),
    (u'CIR',    (u'CIRCLE', u'CRCLE', u'CIRCL', u'CRCL', 'CR', u'CIRC',
                 u'CIR')),
    (u'CIRS',   (u'CIRCLES',)),
    (u'CLB',    (u'CLB', u'CLUB')),
    (u'CLF',    (u'CLIFF', u'CLF')),
    (u'CLFS',   (u'CLIFFS', u'CLFS')),
    (u'CMN',    (u'COMMON',)),
    (u'CMNS',   (u'COMMONS',)),
    (u'COR',    (u'CORNER', u'COR')),
    (u'CORS',   (u'CORS', u'CORNERS')),
    (u'CP',     (u'CMP', u'CAMP', u'CP')),
    (u'CPE',    (u'CPE', u'CAPE')),
    (u'CRES',   (u'CRESCENT', u'CRSNT', u'CRSENT', u'CRES')),
    (u'CRK',    (u'CREEK', u'CRK')),
    (u'CRSE',   (u'CRSE', u'COURSE')),
    (u'CRST',   (u'CREST',)),
    (u'CSWY',   (u'CSWY', u'CAUSEWAY', u'CAUSWA')),
    (u'CT',     (u'COURT', 'QT', u'CT')),
    (u'CTR',    (u'CENTR', u'CNTR', u'CNTER', u'CEN', u'CENTRE', u'CTR',
                 u'CENT', u'CENTER')),
    (u'CTRS',   (u'CENTERS',)),
    (u'CTS',    (u'CTS', u'COURTS')),
    (u'CURV',   (u'CURVE',)),
    (u'CV',     (u'COVE', u'CV')),
    (u'CVS',    (u'COVES',)),
    (u'CYN',    (u'CANYON', u'CNYN', u'CANYN')),
    (u'DL',     (u'DL', u'DALE')),
    (u'DM',     (u'DM', u'DAM')),
    (u'DR',     (u'DR', u'DRIV', u'DRV', u'DRIVE')),
    (u'DRS',    (u'DRIVES',)),
    (u'DV',     (u'DV', u'DIVIDE', u'DVD', u'DIV')),
    (u'EST',    (u'ESTATE', u'EST')),
    (u'ESTS',   (u'ESTATES', u'ESTS')),
    (u'EXPY',   (u'EXPRESS', u'EXPRESSWAY', u'EXPY', u'EXPR', u'EXPW',
                 u'EXP')),
    (u'EXT',    (u'EXTN', u'EXTENSION', u'EXT', u'EXTNSN')),
    (u'EXTS',   (u'EXTS',)),
    (u'FALL',   (u'FALL',)),
    (u'FLD',    (u'FIELD', u'FLD')),
    (u'FLDS',   (u'FIELDS', u'FLDS')),
    (u'FLS',    (u'FALLS', u'FLS')),
    (u'FLT',    (u'FLAT', u'FLT')),
    (u'FLTS',   (u'FLTS', u'FLATS')),
    (u'FRD',    (u'FORD', u'FRD')),
    (u'FRDS',   (u'FORDS',)),
    (u'FRG',    (u'FORG', u'FRG', u'FORGE')),
    (u'FRGS',   (u'FORGES',)),
    (u'FRK',    (u'FORK', u'FRK')),
    (u'FRKS',   (u'FRKS', u'FORKS')),
    (u'FRST',   (u'FORESTS', u'FRST', u'FOREST')),
    (u'FRY',    (u'FERRY', u'FRRY', u'FRY')),
    (u'FT',     (u'FT', u'FORT', u'FRT')),
    (u'FWY',    (u'FRWAY', u'FREEWAY', u'FRWY', u'FREEWY', u'FWY')),
    (u'GDN',    (u'GRDN', u'GARDN', u'GRDEN', u'GARDEN')),
    (u'GDNS',   (u'GRDNS', u'GARDENS', u'GDNS')),
    (u'GLN',    (u'GLN', u'GLEN')),
    (u'GLNS',   (u'GLENS',)),
    (u'GRN',    (u'GRN', u'GREEN')),
    (u'GRNS',   (u'GREENS',)),
    (u'GRV',    (u'GRV', u'GROV', u'GROVE')),
    (u'GRVS',   (u'GROVES',)),
    (u'GTWY',   (u'GATEWY', u'GTWAY', u'GTWY', u'GATEWAY', u'GATWAY')),
    (u'HBR',    (u'HARBR', u'HARB', u'HRBOR', u'HBR', u'HARBOR')),
    (u'HBRS',   (u'HARBORS',)),
    (u'HL',     (u'HILL', u'HL')),
    (u'HLS',    (u'HLS', u'HILLS')),
    (u'HOLW',   (u'HOLW', u'HOLLOW', u'HOLWS', u'HLLW', u'HOLLOWS')),
    (u'HTS',    (u'HT', u'HTS')),
    (u'HVN',    (u'HAVEN', u'HVN')),
    (u'HWY',    (u'HWAY', u'HIGHWAY', u'HIGHWY', u'HWY', u'HIWY', u'HIWAY')),
    (u'INLT',   (u'INLT',)),
    (u'IS',     (u'ISLND', u'IS', u'ISLAND')),
    (u'ISLE',   (u'ISLES', u'ISLE')),
    (u'ISS',    (u'ISLANDS', u'ISS', u'ISLNDS')),
    (u'JCT',    (u'JCTN', u'JCTION', u'JUNCTION', u'JUNCTON', u'JCT',
                 u'JUNCTN')),
    (u'JCTS',   (u'JCTS', u'JCTNS', u'JUNCTIONS')),
    (u'KNL',    (u'KNOL', u'KNOLL', u'KNL')),
    (u'KNLS',   (u'KNOLLS', u'KNLS')),
    (u'KY',     (u'KEY', u'KY')),
    (u'KYS',    (u'KYS', u'KEYS')),
    (u'LAND',   (u'LAND',)),
    (u'LCK',    (u'LCK', u'LOCK')),
    (u'LCKS',   (u'LCKS', u'LOCKS')),
    (u'LDG',    (u'LODG', u'LDG', u'LODGE', u'LDGE')),
    (u'LF',     (u'LOAF', u'LF')),
    (u'LGT',    (u'LGT', u'LIGHT')),
    (u'LGTS',   (u'LIGHTS',)),
    (u'LK',     (u'LK', u'LAKE')),
    (u'LKS',    (u'LAKES', u'LKS')),
    (u'LN',     (u'LN', u'LANE')),
    (u'LNDG',   (u'LNDG', u'LANDING', u'LNDNG')),
    (u'LOOP',   (u'LOOP', u'LOOPS')),
    (u'MALL',   (u'MALL',)),
    (u'MDW',    (u'MEADOW',)),
    (u'MDWS',   (u'MDW', u'MEDOWS', u'MEADOWS', u'MDWS')),
    (u'MEWS',   (u'MEWS',)),
    (u'ML',     (u'MILL',)),
    (u'MLS',    (u'MILLS',)),
    (u'MNR',    (u'MANOR', u'MNR')),
    (u'MNRS',   (u'MNRS', u'MANORS')),
    (u'MSN',    (u'MSSN', u'MISSN')),
    (u'MT',     (u'MT', u'MOUNT', u'MNT')),
    (u'MTN',    (u'MNTAIN', u'MOUNTAIN', u'MOUNTIN', u'MTIN', u'MNTN',
                 u'MTN')),
    (u'MTNS',   (u'MOUNTAINS', u'MNTNS')),
    (u'MTWY',   (u'MOTORWAY',)),
    (u'NCK',    (u'NCK', u'NECK')),
    (u'OPAS',   (u'OVERPASS',)),
    (u'ORCH',   (u'ORCHRD', u'ORCHARD', u'ORCH')),
    (u'OVAL',   (u'OVL', u'OVAL')),
    (u'PARK',   (u'PARKS', u'PRK', u'PARK')),
    (u'PASS',   (u'PASS',)),
    (u'PATH',   (u'PATH', u'PATHS')),
    (u'PIKE',   (u'PIKES', u'PIKE', 'PK')),
    (u'PKWY',   (u'PARKWAYS', u'PKWYS', u'PKWAY', u'PKY', u'PKWY', u'PARKWY',
                 u'PARKWAY')),
    (u'PL',     (u'PL', 'PLACE')),
    (u'PLN',    (u'PLAIN', u'PLN')),
    (u'PLNS',   (u'PLNS', u'PLAINS')),
    (u'PLZ',    (u'PLZA', u'PLAZA', u'PLZ')),
    (u'PNE',    (u'PINE',)),
    (u'PNES',   (u'PINES', u'PNES')),
    (u'PR',     (u'PRR', u'PR', u'PRAIRIE')),
    (u'PRT',    (u'PRT', u'PORT')),
    (u'PRTS',   (u'PORTS', u'PRTS')),
    (u'PSGE',   (u'PASSAGE',)),
    (u'PT',     (u'POINT', u'PT')),
    (u'PTS',    (u'POINTS', u'PTS')),
    (u'RADL',   (u'RADL', u'RADIEL', u'RAD', u'RADIAL')),
    (u'RAMP',   (u'RAMP',)),
    (u'RD',     (u'RD', u'ROAD')),
    (u'RDG',    (u'RDGE', u'RDG', u'RIDGE')),
    (u'RDGS',   (u'RDGS', u'RIDGES')),
    (u'RDS',    (u'ROADS', u'RDS')),
    (u'RIV',    (u'RIVER', u'RIV', u'RIVR', u'RVR')),
    (u'RNCH',   (u'RANCH', u'RNCHS', u'RANCHES', u'RNCH')),
    (u'ROW',    (u'ROW',)),
    (u'RPD',    (u'RAPID', u'RPD')),
    (u'RPDS',   (u'RAPIDS', u'RPDS')),
    (u'RST',    (u'REST', u'RST')),
    (u'RTE',    (u'ROUTE',)),
    (u'RUE',    (u'RUE',)),
    (u'RUN',    (u'RUN',)),
    (u'SHL',    (u'SHL', u'SHOAL')),
    (u'SHLS',   (u'SHLS', u'SHOALS')),
    (u'SHR',    (u'SHR', u'SHORE', u'SHOAR')),
    (u'SHRS',   (u'SHORES', u'SHOARS', u'SHRS')),
    (u'SKWY',   (u'SKYWAY',)),
    (u'SMT',    (u'SUMITT', u'SMT', u'SUMMIT', u'SUMIT')),
    (u'SPG',    (u'SPG', u'SPRING', u'SPRNG', u'SPNG')),
    (u'SPGS',   (u'SPRINGS', u'SPRNGS', u'SPNGS', u'SPGS')),
    (u'SPUR',   (u'SPUR', u'SPURS')),
    (u'SQ',     (u'SQ', u'SQRE', u'SQR', u'SQU', u'SQUARE')),
    (u'SQS',    (u'SQRS', u'SQUARES')),
    (u'ST',     (u'STREE', u'ST', u'STR', u'STREET', u'STRT', u'STS')),
    (u'STA',    (u'STATION', u'STA', u'STN', u'STATN')),
    (u'STRA',   (u'STRAVN', u'STRAV', u'STRVN', u'STRVNUE', u'STRA',
                 u'STRAVENUE', u'STRAVEN')),
    (u'STRM',   (u'STREME', u'STRM', u'STREAM')),
    (u'STS',    (u'STREETS',)),
    (u'TER',    (u'TERR', u'TERRACE', u'TER')),
    (u'TPKE',   (u'TURNPIKE', u'TURNPK', u'TRNPK')),
    (u'TRAK',   (u'TRACKS', u'TRACK', u'TRAK', u'TRK', u'TRKS')),
    (u'TRCE',   (u'TRCE', u'TRACE', u'TRACES')),
    (u'TRFY',   (u'TRAFFICWAY',)),
    (u'TRL',    (u'TRLS', u'TRAIL', u'TRAILS', u'TRL')),
    (u'TRLR',   (u'TRLR', u'TRLRS', u'TRAILER')),
    (u'TRWY',   (u'THROUGHWAY',)),
    (u'TUNL',   (u'TUNEL', u'TUNLS', u'TUNL', u'TUNNL', u'TUNNEL',
                 u'TUNNELS')),
    (u'UN',     (u'UNION', u'UN')),
    (u'UNS',    (u'UNIONS',)),
    (u'UPAS',   (u'UNDERPASS',)),
    (u'VIA',    (u'VIADCT', u'VDCT', u'VIA', u'VIADUCT')),
    (u'VIS',    (u'VISTA', u'VIS', u'VSTA', u'VIST', u'VST')),
    (u'VL',     (u'VL', u'VILLE')),
    (u'VLG',    (u'VILLAGE', u'VILLIAGE', u'VLG', u'VILL', u'VILLAG',
                 u'VILLG')),
    (u'VLGS',   (u'VILLAGES', u'VLGS')),
    (u'VLY',    (u'VLY', u'VALLY', u'VALLEY', u'VLLY')),
    (u'VLYS',   (u'VALLEYS', u'VLYS')),
    (u'VW',     (u'VIEW', u'VW')),
    (u'VWS',    (u'VWS', u'VIEWS')),
    (u'WALK',   (u'WALKS', u'WALK')),
    (u'WALL',   (u'WALL',)),
    (u'WAY',    (u'WY', u'WAY')),
    (u'WAYS',   (u'WAYS',)),
    (u'WL',     (u'WELL',)),
    (u'WLS',    (u'WLS', u'WELLS')),
    (u'XING',   (u'XING', u'CRSSNG', u'CROSSING')),
    (u'XRD',    (u'CROSSROAD',)),
    (u'XRDS',   (u'CROSSROADS',))
]

street_type_replacement_dict = dict([
    (key, replacement)
    for replacement, keys in street_type_replacement_list
    for key in keys
])
